# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=45, verbose_name='Nome da empresa')),
                ('email_responsavel_empresa', models.EmailField(default='', max_length=254, verbose_name='Email do responsável')),
                ('link_da_empresa', models.URLField(default='', verbose_name='Link da Empresa')),
                ('titulo_do_job', models.CharField(default='', max_length=100, verbose_name='Título do job')),
                ('descricao', models.TextField(default='', verbose_name='Descrição do job')),
                ('requisitos', models.TextField(default='', verbose_name='Requisitos para o Job')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data que o job foi adicionado')),
                ('tipo_freela', models.BooleanField(default=1, help_text='Selecione apenas se o job for para freelancers', verbose_name='O job é freela?')),
                ('publico', models.BooleanField(default=0, verbose_name='Este job é público?')),
                ('local', models.CharField(default='Não Especificado', help_text='Preencha com o lugar da vaga, caso seja remota, explicite!', max_length=100, verbose_name='Local da vaga')),
            ],
            options={
                'ordering': ['-data_adicionado'],
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=45)),
                ('email', models.EmailField(default='', max_length=254)),
                ('portfolio', models.URLField(default='')),
                ('data_inscrito', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobs.Freela')),
            ],
        ),
    ]
