# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0002_auto_20170913_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='email_responsavel_empresa',
        ),
        migrations.RemoveField(
            model_name='job',
            name='link_da_empresa',
        ),
        migrations.AlterField(
            model_name='job',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
        migrations.AddField(
            model_name='interestedperson',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='interestedperson',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='interestedperson',
            unique_together=set([('job', 'usuario')]),
        ),
    ]
