# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170913_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedperson',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
