# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170917_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='job',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
