# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170917_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='local',
            field=models.CharField(default='', help_text='Preencha com o lugar da vaga, caso seja remota, explicite!', max_length=100, verbose_name='Local da vaga'),
        ),
    ]
