# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170917_2354'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
