# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170919_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestedperson',
            options={'verbose_name': 'Pessoa Interessada', 'verbose_name_plural': 'Pessoas Interessadas'},
        ),
    ]
