# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20171101_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='nivel',
            field=models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior')], default=None, max_length=30, verbose_name='Nível'),
            preserve_default=False,
        ),
    ]
