# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20171101_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salario_maximo',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='Salário máximo'),
        ),
        migrations.AddField(
            model_name='job',
            name='salario_minimo',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='Salário mínino'),
        ),
    ]
