# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 12:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, default="", verbose_name="GitHub"),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True, default="", verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolio",
            field=models.URLField(blank=True, default="", verbose_name="Portfolio"),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
