# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180411_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Público?'),
        ),
    ]
