# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='', verbose_name='Requisitos da vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='', verbose_name='Descrição da vaga'),
        ),
    ]
