# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180511_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ad_interested',
            field=models.BooleanField(default=False, verbose_name='Interessado em ficar em destaque no PyJobs?'),
        ),
    ]
