# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0015_job_ad_interested")]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_title",
                    models.TextField(default="", verbose_name="Título do E-mail"),
                ),
                (
                    "message_content",
                    models.TextField(default="", verbose_name="Texto do E-mail"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="ad_interested",
            field=models.BooleanField(
                default=False,
                verbose_name="Tenha a vaga destacada e tenha 4x mais currículos",
            ),
        ),
    ]
