# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0017_auto_20181111_1844")]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="message_type",
            field=models.CharField(
                default="",
                max_length=200,
                verbose_name="Ticker usado no backend para ID da msg",
            ),
        )
    ]
