# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0020_skills")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(to="core.Skills"),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(to="core.Skills"),
        ),
    ]
