# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0021_auto_20190120_2135")]

    operations = [
        migrations.AlterModelOptions(
            name="job", options={"ordering": ("-created_at",)}
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["created_at"], name="core_job_created_8e7744_idx"
            ),
        ),
    ]
