# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0022_use_created_at_to_order_jobs")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="ad_interested",
            field=models.BooleanField(default=False, verbose_name="Impulsionar*"),
        ),
        migrations.AlterField(
            model_name="job",
            name="application_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Ex.: http://goo.gl/hahaha",
                verbose_name="Link para a Vaga",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_email",
            field=models.EmailField(
                help_text="Ex.: abc@def.com",
                max_length=254,
                verbose_name="Email da Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(
                default="",
                help_text="Ex.: ACME Inc",
                max_length=100,
                verbose_name="Nome da Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                default="",
                help_text="Descreva um pouco da sua empresa e da vaga, tente ser breve",
                verbose_name="Descrição da vaga",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.TextField(
                default="",
                help_text="Descreva os requisitos da sua empresa em bullet points\n\n-Usar Git\n-Saber Java",
                verbose_name="Requisitos da vaga",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                default="",
                help_text="Ex.: Desenvolvedor",
                max_length=100,
                verbose_name="Título da Vaga",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="workplace",
            field=models.CharField(
                default="",
                help_text="Ex.: Santana - São Paulo",
                max_length=100,
                verbose_name="Local",
            ),
        ),
    ]
