# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190515_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Vaga aberta'),
        ),
    ]
