# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_is_open_to_job"),
        ("core", "0029_auto_20190620_2254"),
    ]

    operations = []
