# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0032_auto_20190705_0906")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cellphone",
            field=models.CharField(
                help_text="Deixe seu WhatsApp para contatarmos sobre nossos serviços",
                max_length=16,
                null=True,
                verbose_name="WhatsApp para contato",
            ),
        )
    ]
