# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0033_job_cellphone")]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="", max_length=254, verbose_name="Email"),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="Nome"),
                ),
                (
                    "slug",
                    models.CharField(default="", max_length=100, verbose_name="Slug"),
                ),
            ],
        )
    ]
