# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='challenge',
            field=models.TextField(blank=True, null=True, verbose_name='Challenge'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_challenging',
            field=models.BooleanField(default=False, verbose_name='Enviar Chall'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='challenge_response_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 17, 7, 38, 103960)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='challenge_response_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
