# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190828_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='challenge_response_at',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
