# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190828_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='challenge_interested',
            field=models.BooleanField(default=False, verbose_name='Desafio*'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='challenge_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='challenge_response_link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Link de resposta ao desafio'),
        ),
    ]
