# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0036_auto_20190917_1821")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="challenge_resent",
            field=models.BooleanField(default=False),
        )
    ]
