# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190828_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
