# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0038_jobapplication_email_sent_at")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="challenge_interested",
            field=models.BooleanField(default=False, verbose_name="Desafio*"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="challenge_response_link",
            field=models.URLField(
                blank=True,
                default="",
                null=True,
                verbose_name="Link de resposta ao desafio",
            ),
        ),
    ]
