# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-09 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0039_auto_20191009_1913")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
