# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0040_auto_20191009_2102")]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="output_sent",
            field=models.BooleanField(default=False),
        )
    ]
