# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_jobapplication_output_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="receive_emails",
            field=models.BooleanField(default=True, verbose_name="Enviar emails?"),
        ),
    ]
