# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20191101_0019'),
    ]

    database_operations = [
        migrations.AlterModelTable('Messages', 'marketing_messages'),
    ]

    state_operations = [
        migrations.DeleteModel('Messages')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
