# Generated by Django 2.2.8 on 2020-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_auto_20191101_0911"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="on_mailing_list",
            field=models.BooleanField(
                default=False, verbose_name="Está na mailing list"
            ),
        ),
    ]
