# Generated by Django 2.2.13 on 2020-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_auto_20200812_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="company_feedback",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="company_feedback_type",
            field=models.IntegerField(
                choices=[(1, "Sem feedback"), (2, "Positivo"), (3, "Negativo")],
                default=5,
                verbose_name="Tipo de feedback",
            ),
        ),
    ]
