# Generated by Django 2.2.13 on 2020-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_auto_20200816_1029"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="agree_privacy_policy",
            field=models.BooleanField(
                default=True, verbose_name="Aceitou políticas de privacidade"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="company_feedback_type",
            field=models.IntegerField(
                choices=[(1, "Sem feedback"), (2, "Aprovado"), (3, "Reprovado")],
                default=5,
                verbose_name="Tipo de feedback",
            ),
        ),
    ]
