# Generated by Django 3.1.2 on 2020-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_auto_20200902_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="issue_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Issue do Github"
            ),
        ),
    ]
