# Generated by Django 3.1.2 on 2021-01-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_skill_unique_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Descrição da skill"
            ),
        ),
    ]
