# Generated by Django 3.1.2 on 2021-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_auto_20210202_1134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_range",
            field=models.IntegerField(
                choices=[
                    (1, "0,00 - 1.000,00"),
                    (2, "1.000,01 - 3.000,00"),
                    (3, "3.000,01 - 6.000,00"),
                    (4, "6.000,01 - 10.000,00"),
                    (5, "10.000,01 - 13.000,00"),
                    (6, "13.000,01 - 16.000,00"),
                    (7, "16.000,01 - 19.000,00"),
                    (8, "19.000,01 - 21.000,00"),
                    (9, "21.000,01 - +"),
                    (10, "NI"),
                ],
                default=1,
                verbose_name="Faixa Salarial",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="salary_range",
            field=models.IntegerField(
                choices=[
                    (1, "0,00 - 1.000,00"),
                    (2, "1.000,01 - 3.000,00"),
                    (3, "3.000,01 - 6.000,00"),
                    (4, "6.000,01 - 10.000,00"),
                    (5, "10.000,01 - 13.000,00"),
                    (6, "13.000,01 - 16.000,00"),
                    (7, "16.000,01 - 19.000,00"),
                    (8, "19.000,01 - 21.000,00"),
                    (9, "21.000,01 - +"),
                    (10, "NI"),
                ],
                default=6,
                verbose_name="Sua Faixa Salarial Atual",
            ),
        ),
    ]
