# Generated by Django 3.1.2 on 2021-02-02 11:28

from django.db import migrations, models
import django.db.models.deletion


def create_country_and_currency(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Country = apps.get_model("core", "Country")
    Country.objects.using(db_alias).create(name="Brasil")

    Currency = apps.get_model("core", "Currency")
    Currency.objects.using(db_alias).create(name="Real", slug="BRL")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210202_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Ex.: Brasil', max_length=300, verbose_name='Nome do País'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='Ex.: Euro', max_length=300, verbose_name='Nome da Moeda'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.CharField(help_text='Ex.: EUR', max_length=300, verbose_name='Abreviação'),
        ),
        migrations.RunPython(create_country_and_currency),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.currency'),
        ),
    ]
