# Generated by Django 3.1.2 on 2021-02-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_job_unique_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="unique_slug",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                unique=True,
                verbose_name="Slug Unica",
            ),
        ),
    ]
