# Generated by Django 3.1.7 on 2021-03-09 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0059_auto_20210306_1727"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skillproficiency",
            unique_together={("user", "skill")},
        ),
    ]
