# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0045_auto_20191101_0911"),
        ("marketing", "0002_auto_20191101_0912"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_receiving_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail para enviarmos a indicação"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Job"
                    ),
                ),
                (
                    "user_sharing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Indicação", "verbose_name_plural": "Indicações",},
        ),
        migrations.AlterModelTable(name="messages", table=None,),
    ]
