# Generated by Django 2.2.7 on 2019-12-03 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_customerquote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.Job"
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="user_sharing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
