# Generated by Django 3.1.2 on 2021-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_auto_20191203_1636"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head", models.CharField(max_length=2000, verbose_name="Titulo")),
                (
                    "body",
                    models.TextField(max_length=2000, verbose_name="Texto da mensagem"),
                ),
                ("url", models.URLField(verbose_name="Link para a vaga")),
            ],
        ),
    ]
