# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('empresa_ou_pessoa', models.BooleanField(default=False)),
            ],
        ),
    ]
