# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prospects',
            new_name='Prospect',
        ),
    ]
