# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 02:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=45, verbose_name='Nome da empresa')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email do responsável da empresa')),
                ('site', models.URLField(default='', verbose_name='Link da Empresa')),
                ('descricao', models.TextField(default='', verbose_name='Descreva um pouco da empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone inválido! Digite entre 11 e 15 caracteres que podem conter números, espaços, parênteses e hífen.', regex='^((?:\\([1-9]{2}\\)|\\([1-9]{2}\\) |[1-9]{2}|[1-9]{2} )(?:[2-8]|9[1-9])[0-9]{3}(?:\\-[0-9]{4}| [0-9]{4}|[0-9]{4}))$')], verbose_name='Telefone')),
                ('github', models.URLField(default='', verbose_name='URL do seu GitHub')),
                ('linkedin', models.URLField(default='', verbose_name='URL do seu Linkedin')),
                ('portfolio', models.URLField(default='', verbose_name='URL do seu Portfolio')),
                ('habilidades', models.TextField(default='', verbose_name='Habilidades que você tem')),
                ('plano_de_cv_db', models.BooleanField(default=False, verbose_name='A conta tem acesso ao plano_de_cv_db')),
                ('data_inscrito', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
