# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170916_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interesse_banco_cv',
            field=models.BooleanField(default=False, verbose_name='Você tem interesse em receber novas propostas de empresas?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plano_de_cv_db',
            field=models.BooleanField(default=False, verbose_name='A conta tem acesso ao Banco de Curriculos'),
        ),
    ]
