# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170917_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
