# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170917_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, default='', verbose_name='URL do seu GitHub'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interesse_banco_cv',
            field=models.BooleanField(default=True, verbose_name='Você tem interesse em receber novas propostas de empresas?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='URL do seu Linkedin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.URLField(blank=True, default='', verbose_name='URL do seu Portfolio'),
        ),
    ]
