# Generated by Django 3.1.7 on 2021-03-09 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("random_order", models.BooleanField(default=False)),
                (
                    "time_limit",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("pt", "Portuguese"), ("en", "English")],
                        max_length=500,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=5000)),
                ("correct_answer", models.CharField(max_length=5000)),
                ("first_incorrect_answer", models.CharField(max_length=5000)),
                ("second_incorrect_answer", models.CharField(max_length=5000)),
                ("third_incorrect_answer", models.CharField(max_length=5000)),
                ("forth_incorrect_answer", models.CharField(max_length=5000)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.assessment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.assessmentcategory",
            ),
        ),
    ]
