# Generated by Django 3.1.7 on 2021-03-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="slug",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="assessmentcategory",
            name="slug",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
