# Generated by Django 3.1.7 on 2021-03-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_auto_20210309_1908"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentcategory",
            name="description",
            field=models.CharField(default="", max_length=5000),
            preserve_default=False,
        ),
    ]
