# Generated by Django 3.1.7 on 2021-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_assessment_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="random_order",
        ),
        migrations.AlterField(
            model_name="assessment",
            name="description",
            field=models.TextField(max_length=5000),
        ),
    ]
