# Generated by Django 3.1.7 on 2021-03-30 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessment", "0007_auto_20210309_2122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"verbose_name": "Teste", "verbose_name_plural": "Testes"},
        ),
        migrations.AlterModelOptions(
            name="assessmentcategory",
            options={
                "verbose_name": "Categoria do Teste",
                "verbose_name_plural": "Categorias dos Testes",
            },
        ),
        migrations.AlterModelOptions(
            name="punctuation",
            options={"verbose_name": "Pontuação", "verbose_name_plural": "Pontuações"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Pergunta", "verbose_name_plural": "Perguntas"},
        ),
        migrations.AlterUniqueTogether(
            name="punctuation",
            unique_together={("user", "question")},
        ),
    ]
