# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Freela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=45)),
                ('email_responsavel_empresa', models.EmailField(default='', max_length=254)),
                ('link_da_empresa', models.URLField(default='')),
                ('titulo_do_job', models.CharField(default='', max_length=100)),
                ('link_job', models.URLField(default='')),
                ('descricao', models.TextField(default='')),
                ('requisitos', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
