# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freela',
            name='link_job',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
