# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freela', '0002_auto_20170727_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='freela',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
