# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freela', '0003_freela_data_adicionado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freela',
            options={'ordering': ['-data_adicionado']},
        ),
        migrations.AddField(
            model_name='freela',
            name='freela_ou_vaga',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='freela',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
