# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freela', '0004_auto_20170808_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freela',
            old_name='freela_ou_vaga',
            new_name='tipo_freela',
        ),
    ]
