# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freela', '0005_auto_20170808_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freela',
            name='link_job',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='freela.Freela'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='nome',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='portfolio',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='freela',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
