# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freela', '0006_auto_20170809_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='freela',
            name='publico',
            field=models.BooleanField(default=0),
        ),
    ]
