# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freela', '0008_freelancer_data_inscrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freela',
            name='valor_pago',
        ),
        migrations.AlterField(
            model_name='freela',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data que o job foi adicionado'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição do job'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='email_responsavel_empresa',
            field=models.EmailField(default='', max_length=254, verbose_name='Email do responsável'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='empresa',
            field=models.CharField(default='', max_length=45, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='link_da_empresa',
            field=models.URLField(default='', verbose_name='Link da Empresa'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='publico',
            field=models.BooleanField(default=0, verbose_name='Este job é público?'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='requisitos',
            field=models.TextField(default='', verbose_name='Requisitos para o Job'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='tipo_freela',
            field=models.BooleanField(default=1, help_text='Selecione apenas se o job for para freelancers', verbose_name='O job é freela?'),
        ),
        migrations.AlterField(
            model_name='freela',
            name='titulo_do_job',
            field=models.CharField(default='', max_length=100, verbose_name='Título do job'),
        ),
    ]
