# Generated by Django 2.2.7 on 2019-12-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0045_auto_20191101_0911"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254)),
                ("company_address", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("related_jobs", models.ManyToManyField(to="core.Job")),
                ("skills", models.ManyToManyField(to="core.Skill")),
            ],
        ),
    ]
