# Generated by Django 2.2.7 on 2019-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_auto_20191208_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="company_address",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Site da empresa"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição da empresa"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email da empresa"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="related_jobs",
            field=models.ManyToManyField(blank=True, to="core.Job"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="skills",
            field=models.ManyToManyField(blank=True, to="core.Skill"),
        ),
    ]
