# Generated by Django 2.2.7 on 2019-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_auto_20191208_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="logo_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Logo da empresa"
            ),
        ),
    ]
