# Generated by Django 2.2.8 on 2020-01-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partner_logo_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner", options={"verbose_name": "Parceiro"},
        ),
    ]
