import os

from django.core.management.base import BaseCommand
from django.db import IntegrityError

from pyjobs.core.models import Skill


class Command(BaseCommand):
    def _get_skills(self):
        return [
            "Ajax",
            "Amazon API",
            "Amazon EC2",
            "Amazon S3",
            "Android SDK",
            "AngularJS",
            "Apache",
            "API",
            "Appcelerator",
            "AppExchange",
            "Apple",
            "ArcGIS",
            "Arch Linux",
            "Augmented Reality",
            "AWK",
            "AWS",
            "Azure",
            "Backbone.js",
            "Basecamp",
            "BFC",
            "Big Data Architects",
            "Bing Maps",
            "Bitcoin",
            "BlackBerry",
            "Blender",
            "Blockchain",
            "BlueBream",
            "Bluetooth",
            "BoonEx",
            "Bootstrap",
            "Bottle",
            "Brew",
            "Brutos Framework",
            "BuddyPress",
            "Business Intelligence",
            "C",
            "C#",
            "C++",
            "CartoDB",
            "Cassandra",
            "Catalyst",
            "Caveman2",
            "CFWheels",
            "Chatbot",
            "CherryPy",
            "CiviCRM",
            "Clarion",
            "Clojure",
            "CMS",
            "CoffeeScript",
            "Cognos",
            "ColdBox Platform",
            "concrete5",
            "Core Java",
            "Corona SDK",
            "CppCMS",
            "CRM",
            "Cross-Platform",
            "Crystal Reports",
            "CSLA",
            "CSS",
            "CTOs",
            "CubicWeb",
            "CUDA",
            "Cython",
            "D",
            "D3.js",
            "Data Scientists",
            "Deep Learning Experts",
            "Demandware",
            "DevExpress",
            "DirectX",
            "Django",
            "Dojo",
            "DotNetNuke",
            "Dropbox",
            "Drupal",
            "eCommerce",
            "EDI",
            "Elasticsearch",
            "Elgg",
            "Elixir",
            "Ember.js",
            "Erlang",
            "ERP",
            "ETL",
            "Evernote",
            "Excel",
            "Expedia",
            "ExpressionEngine",
            "Express.js",
            "Ext JS",
            "F#",
            "Facebook Ads",
            "Facebook API",
            "Fat-Free",
            "FileMaker",
            "Firebase",
            "Fitbit",
            "Flash",
            "Flask",
            "Flex",
            "Force.com",
            "FormEngine",
            "Fortran",
            "FoxPro",
            "FPGA",
            "FreeBSD",
            "Friendster",
            "FuelPHP",
            "Fusebox",
            "Gentoo",
            "GIMP",
            "GIS",
            "GitHub",
            "Gmail",
            "Go",
            "Google API",
            "Google Web Toolkit",
            "Grails",
            "Grok",
            "Groovy",
            "Groupon",
            "Gulp Experts",
            "Hadoop",
            "Hamlets",
            "Happstack",
            "Haskell",
            "Hazaar MVC",
            "Heroku",
            "HFT",
            "hi5",
            "Hibernate",
            "HTML5",
            "HubSpot",
            "Hybris",
            "iAd",
            "iBeacon",
            "iCloud",
            "IMS",
            "Informatica",
            "Infusionsoft",
            "Instagram API",
            "Ionic",
            "iOS",
            "iPad",
            "iPhone App Development Freelancer",
            "IT",
            "ItsNat",
            "Jade",
            "Java",
            "Java EE",
            "JavaScript",
            "JavaServer Faces",
            "JBoss",
            "JBoss Seam",
            "JIRA",
            "JMS",
            "jQuery",
            "JSP",
            "Jspx-bay",
            "JVx",
            "Kajona",
            "Kindle",
            "Knockout.js",
            "Kohana",
            "Kotlin",
            "Kubernetes Experts",
            "LabVIEW",
            "LAMP",
            "Laravel",
            "Layar",
            "Leap Motion",
            "Lift",
            "Lightning",
            "LinkedIn API",
            "Linux",
            "Lithium",
            "LMS",
            "Lotus Notes",
            "Lua",
            "Mach-II",
            "Machine Learning",
            "Magento",
            "MailChimp",
            "MapQuest",
            "Mason",
            "MATLAB",
            "Maya",
            "Maypole",
            "MEAN Stack",
            "Mega",
            "Merb",
            "Meteor",
            "Microsoft",
            "Microsoft Access",
            "Microsoft Dynamics CRM",
            "Microsoft Kinect",
            "Model-Glue",
            "MODx",
            "Mojolicious",
            "Moneybookers",
            "MongoDB",
            "Mono",
            "MonoRail",
            "Moodle",
            "MS SQL",
            "MySQL",
            "Nagare",
            "Neo4j",
            ".NET",
            "NetBSD",
            "NetSuite",
            "Nette Framework",
            "Nexus",
            "Node.js",
            "nopCommerce",
            "Objective-C",
            "OCaml",
            "Octave",
            "Oculus Rift",
            "Odoo",
            "OneDrive",
            "OpenBSD",
            "OpenCart",
            "OpenCV",
            "OpenERP",
            "OpenGL",
            "OpenLaszlo",
            "OpenRasta",
            "OpenSocial",
            "OpenStack",
            "OpenUI5",
            "OpenXava",
            "Oracle",
            "Oracle ADF",
            "Oracle Forms",
            "Oracle SQL",
            "osCommerce",
            "Padrino",
            "Parse",
            "PayPal",
            "Pebble",
            "Perl",
            "Phalcon",
            "Phoenix",
            "PhoneGap",
            "Photoshop",
            "PHP",
            "phpBB",
            "PHPfox",
            "PHPixie",
            "Play",
            "Plone",
            "PL/SQL",
            "Pocket",
            "Poco",
            "POS",
            "PostgreSQL",
            "PowerBuilder",
            "PRADO",
            "PrestaShop",
            "Prezi",
            "Prototype",
            "PureMVC",
            "Pyjs",
            "Pylons",
            "PyObjC",
            "PyQt",
            "Pyramid",
            "Python",
            "QlikView",
            "Qt",
            "Quantitative",
            "QuickBase",
            "QuickBooks",
            "R",
            "Rackspace",
            "Ractive.js",
            "Raspberry Pi",
            "React.js",
            "React Native",
            "RIFE",
            "RSS",
            "Ruby",
            "Ruby on Rails",
            "SaaS",
            "Saetta Web Server",
            "Sails.js",
            "Salesforce",
            "Salesforce1",
            "SAP",
            "SAS",
            "Sass",
            "SCADA",
            "Scala",
            "Scalatra",
            "Selenium",
            "Sencha Touch",
            "SharePoint",
            "Shopify",
            "Silex",
            "Silverlight",
            "SilverStripe",
            "Sinatra",
            "Sitecore",
            "Sitefinity",
            "Slack",
            "Smarty",
            "SMS",
            "Snap",
            "SOA",
            "Socket.IO",
            "Solaris",
            "SOLIDWORKS",
            "Spark",
            "Spotify",
            "Spree Commerce",
            "Spring",
            "SQL",
            "SQL CLR",
            "SQL Server",
            "SSIS",
            "Stripe",
            "Stripes",
            "Struts",
            "SugarCRM",
            "SUN",
            "SVG",
            "Sybase",
            "Symbian",
            "Symfony",
            "Sys Admins",
            "Tableau",
            "TACTIC",
            "Takes",
            "Technical Writers",
            "Telerik",
            "Teradata",
            "ThinWire",
            "TIBCO",
            "Titanium",
            "Tizen",
            "Tntnet",
            "TokBox",
            "Tornado",
            "Tumblr",
            "TurboGears",
            "Twilio",
            "Twitter",
            "Twitter Bootstrap",
            "TypeScript",
            "TYPO3",
            "TYPO3 Flow",
            "Uber",
            "Ubuntu",
            "UI",
            "Umbraco",
            "UML",
            "Unified.js",
            "Unity or Unity3D",
            "Unix",
            "UX",
            "Vaadin",
            "VBA",
            "VB.NET",
            "vBulletin",
            "Velocity",
            "Vibe.d",
            "Vimeo",
            "Vine",
            "Virtual Reality",
            "Visio",
            "Visual Basic",
            "Visualforce",
            "Visual Studio",
            "Volusion",
            "VRaptor",
            "VSS",
            "vTiger",
            "Vue.js",
            "Vuforia",
            "Wavemaker",
            "web2py",
            "WebKit",
            "WebObjects",
            "webOS",
            "WebRTC",
            "WebSphere",
            "Webware",
            "WebWork",
            "Weebly",
            "WHMCS",
            "Windows",
            "Windows Phone",
            "WooCommerce",
            "WordPress",
            "Wowza",
            "WPF",
            "Wt",
            "Xamarin",
            "Xbox",
            "Xcode",
            "Xero",
            "XML",
            "XNA",
            "XP",
            "Yahoo! Store",
            "Yelp API",
            "Yesod",
            "Yii",
            "Yii 2",
            "YouTube API",
            "Ze Framework",
            "Zend",
            "Zendesk",
            "ZK",
            "Zope 2",
            "ztemplates",
        ]

    def handle(self, *args, **options):
        qs_skills = Skill.objects.all()
        skills = self._get_skills()
        for skill in skills:
            skill_obj = Skill.objects.create(name=skill.strip())

        return "True"
